[[default]]
names = [
  "helix",
  "alacritty",
  "zellij",
]
to = "~/.config"

[[linux]]
names = [
  "nushell",
]
to = "~/.config"

[[macos]]
names = [
  "nushell",
]
to = "~/Library/Application Support/"
