theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
rulers = [
  100,
]

[editor.indent-guides]
render = true

# [editor.cursor-shape]
# insert = "underline"
# normal = "block"
# select = "underline"
