theme = "gruvbox_dark_hard_modified"

[editor]
shell = ["nu", "--no-newline", "--stdin", "-c"]
line-number = "relative"
cursorline = true
rulers = [
  100,
]

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

# [editor.cursor-shape]
# insert = "underline"
# normal = "block"
# select = "underline"

# keybindings -------------------------------------------------------------------------------------
[keys.normal]
C-y = ":clipboard-yank"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
"!" = ["insert_at_line_start", "normal_mode"]
"@" = ["insert_at_line_end", "normal_mode", "move_char_left"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
C-y = ":clipboard-yank"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
